import pandas as pd
import os


input_df = pd.read_csv(config['input_csv'])
timestamp_col = str(config['timestamp_col'])
filepath_col = str(config['filepath_col'])

shapefilepaths = {}
catalog_filepaths = {}
startdates = {}
enddates = {}
export_folderpaths = {}
final_outputs = []

FINAL_OUTFILENAME = 'done.txt' # see: function create_planet_datacube.py


for index, row in input_df.iterrows():
    roi = row['roi']
    catalog_filepath = row['catalog_filepath']
    shapefilepath = row['shapefilepath']
    startdate = pd.to_datetime(row['startdate'])
    enddate = pd.to_datetime(row['enddate'])
    export_folderpath = os.path.join(
        root_folderpath,
        roi,
        f"{startdate.strftime('%Y%m%dT%H%M%S')}_{enddate.strftime('%Y%m%dT%H%M%S')}",
        config_id,
    )
    export_folderpath = os.path.abspath(export_folderpath)
    final_output = os.path.join(export_folderpath, FINAL_OUTFILENAME)
    shapefilepaths[final_output] = shapefilepath
    catalog_filepaths[final_output] = catalog_filepath
    startdates[final_output] = startdate.strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + 'Z'
    enddates[final_output] = enddate.strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + 'Z'
    export_folderpaths[final_output] = export_folderpath
    final_outputs.append(final_output)


rule all:
    input:
        expand('{final_output}', final_output=final_outputs)

rule run:
    output:
        '{final_output}'

    params:
        shapefilepath = lambda wc: shapefilepaths[wc.final_output],
        catalog_filepath = lambda wc: catalog_filepaths[wc.final_output],
        startdate = lambda wc: startdates[wc.final_output],
        enddate = lambda wc: enddates[wc.final_output],
        config_id = lambda wc: config_ids[wc.final_output],
        export_folderpath = lambda wc: export_folderpaths[wc.final_output],
        param_timestamp_col = timestamp_col
        param_filepath_col = filepath_col

    threads: 1

    shell:
        (
            "python ../../scripts/create_planet_datacube.py "
            "{params.shapefilepath} "
            "{params.catalog_filepath} "
            "{params.param_timestamp_col} "
            "{params.param_filepath_col} "
            "{params.startdate} "
            "{params.enddate} "
            "{params.export_folderpath} "
        )
